#!/usr/local/bin/python
# -*- coding: utf8 -*-

# search osm
# ErshKUS

from sphinxapi import *
import cgi, sys, json
import psycopg2
import db_config

host = 'localhost'
port = 3312
listAddrType=['city','district','region']
countlistAddrType=2
q = ''
q2 = ''

mode=SPH_MATCH_EXTENDED2
lat = 0
lon = 0

output={}
output['ver']='0.5'

def main():
  def ifresult(res):
    if not res:
      output['error']='query failed: %s' % cl.GetLastError()
      return 11
    if cl.GetLastWarning():
      output['error']='WARNING: %s\n' % cl.GetLastWarning()
      return 12
    if not res['total_found']:
      return 1
    return 2
    
  def regeo(addrType):
  
    conn = psycopg2.connect(host=db_config.addr_host, database=db_config.addr_database, user=db_config.addr_user, password=db_config.addr_password)
    cur = conn.cursor()
    execute = """
      SELECT region_id, district_id, city_id
      FROM ershkus_search_addr
      WHERE
        (geom && (ST_GeomFromText('POINT(%(lon)s %(lat)s)',4326))) AND ST_Covers(geom, (ST_GeomFromText('POINT(%(lon)s %(lat)s)',4326)))
        AND (full_name is not null AND full_name <> '')
        AND addr_type='%(addrType)s'
    """ % {"lat":lat, "lon":lon, "addrType":addrType}
    cur.execute(execute)
    regeo=cur.fetchone()
    return regeo
    
  print "Content-type: text/javascript; Charset=Utf-8\nAccess-Control-Allow-Origin: *\n" # debug
  #print "Content-type: application/json; Charset=Utf-8\nAccess-Control-Allow-Origin: *\n" # production
  values=cgi.FieldStorage()
  q = values.getfirst("q","")
  lat = float(values.getfirst("lat","0"))
  lon = float(values.getfirst("lon","0"))
  asis = bool(values.getfirst("asis",""))
  nolimit = bool(values.getfirst("nolimit",""))
  cnt = int(values.getfirst("cnt","12"))
  output['search']=q
  if not asis :
    output['search'] = output['search'].replace('&','&amp;')
    output['search'] = output['search'].replace('\"',"&quot;")
    output['search'] = output['search'].replace('\'','&#039;')
    output['search'] = output['search'].replace('<','&lt;')
    output['search'] = output['search'].replace('>','&gt;')
  if not q:
    output['error']="no query words, 'q' is empty"
    return
  
  
  cl = SphinxClient()
  cl.SetServer ( host, port )
  cl.SetMatchMode ( mode )
  
  cl.SetRankingMode(SPH_RANK_SPH04)
  
  if (lat and lon):
    cl.SetGeoAnchor("lat", "lon", lat, lon)
    cl.SetSortMode ( SPH_SORT_EXTENDED, '@weight desc addr_type_id asc @geodist ASC' )
    #cl.SetSortMode ( SPH_SORT_EXPR, '@weight/@geodist' )
  else:
    cl.SetSortMode ( SPH_SORT_EXTENDED, '@weight desc addr_type_id asc' )
  
  #cl.SetFilterRange('@relevance', 10, 10000)
  #cl.SetSelect ( "*, @expr AS myweight" )
  
  if (cnt and (not nolimit)):
    cl.SetLimits ( 0, cnt, max(cnt,1000) )
  
  q = q.replace("-"," \-")
  q = q.replace("/","\/")

  resQ=1
  if (lat and lon):
    for xAddrType in listAddrType:
      q2 = regeo(xAddrType)
      if q2 == None:
        continue
      i=countlistAddrType
      cl.ResetOnlyFilter()
      for n in q2:
        if n <> None:
          cl.SetFilter(listAddrType[i]+'_id',[n])
        i=i-1
      res = cl.Query(q)
      resQ=ifresult(res)
      if resQ > 10:
        return
      if resQ == 2:
        break
    
  if resQ == 1:
    cl.ResetOnlyFilter()
    res = cl.Query(q)
    resQ2 = ifresult(res)
    if resQ2 > 10:
      return
    if resQ2 == 1:
      output['find']=False
      return
  
  if res.has_key('matches'):
    output['find']=True
    outputdata=[]
    weight_min=(res['matches'][0]['weight']-100)
    for match in res['matches']:
      
      if (match['weight']>weight_min) :
        outputlen=match['attrs']
        outputlen['id']=match['id']
        outputlen['weight']=match['weight']
        if not asis :
          outputlen['display_name'] = outputlen['display_name'].replace('&','&amp;')
          outputlen['display_name'] = outputlen['display_name'].replace('\"',"&quot;")
          outputlen['display_name'] = outputlen['display_name'].replace('\'','&#039;')
          outputlen['display_name'] = outputlen['display_name'].replace('<','&lt;')
          outputlen['display_name'] = outputlen['display_name'].replace('>','&gt;')
        outputdata.append(outputlen)
      
  output['matches']=outputdata
  
main()
print json.dumps(output)
